// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// smacof
Rcpp::NumericMatrix smacof(NumericMatrix diss, NumericMatrix w, NumericMatrix initConf, int niter, double eps, bool verbose);
RcppExport SEXP FisHiCal_smacof(SEXP dissSEXP, SEXP wSEXP, SEXP initConfSEXP, SEXP niterSEXP, SEXP epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type diss(dissSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type initConf(initConfSEXP );
        Rcpp::traits::input_parameter< int >::type niter(niterSEXP );
        Rcpp::traits::input_parameter< double >::type eps(epsSEXP );
        Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP );
        Rcpp::NumericMatrix __result = smacof(diss, w, initConf, niter, eps, verbose);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
